image: mg92/trion-rsync:latest

before_script:
  - mkdir -p ~/.ssh
  - npm install @angular-devkit/build-angular
  - npm link
  - echo -e "$DEPLOY_KEY" > ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

stages:
  - deploy

# Deploy variables need to be set in
# https://gitlab.com/{user}/{project}/settings/repository
Deploy:
  stage: deploy
  script:
    - npm run build:website
    - rsync -avz -e "ssh -o StrictHostKeyChecking=no" --progress ./dist/website/* root@167.86.100.47:/var/www/html
  only:
    - master

