image: mg92/trion-rsync:latest

# Folder is cached between builds
# Watch when adding dependencies
cache:
  paths:
    - node_modules/

before_script:
  - mkdir -p ~/.ssh
  - npm install @angular-devkit/build-angular
  - echo -e "$DEPLOY_KEY" > ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

stages:
  - test-app
  - publish-lib
  - deploy

Lint and Test App:
  stage: test-app
  script:
    - npm run -- ng lint kinam
    - npm run -- ng test kinam --watch=false --progress=false
  only:
    - develop

# Deploy variables need to be set in
# https://gitlab.com/{user}/{project}/settings/repository
Deploy:
  stage: deploy
  script:
    - npm run -- ng build --progress=false --prod
    - rsync -avz -e "ssh -o StrictHostKeyChecking=no" --progress ./dist/kinam/* root@173.212.231.161:/var/www/html/kinam
  only:
    - master

